### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'str' and 'str'

### ISSUE THREAD

**Issue by delbronski** [protibimbok/django-vite-plugin#43]
Hey, cool project. But could not get it to work in python v3.11.6. I get the following error: 

TypeError: unsupported operand type(s) for /: 'str' and 'str'

Seems like in a few places you are using this kind of syntax:

getattr(settings, 'BASE_DIR') / 'static' and python thinks you are trying to divide strings.

**Comment by protibimbok** [comment]
How can I re-create this error?

**Comment by jbuerklin** [comment]
@delbronski the problem might be that you're using an outdated version of Django.  
Django 3.1 changed the way how `BASE_DIR` is defined.  
Prior to 3.1 it was a string, defined as
```python
import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
```

Recent versions implement it as
```python
from pathlib import Path
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent
```
with the advantage that `pathlib.path` objects can be concatenated using `/`, as in your example: `BASE_DIR / 'static' ` instead of `os.path.join(BASE_DIR, 'static')`
